name: Build APK with Emulator

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armv7, arm64]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Start Android emulator
      uses: docker://budtmo/docker-android:emulator_11.0
      with:
        args: >
          -e EMULATOR_DEVICE="Nexus 5"  # Use a simpler device
          -e EMULATOR_ARGS="-no-window -no-audio -no-boot-anim -gpu swiftshader_indirect -no-snapshot -partition-size 2048"
          -e WEB_VNC=false  # Disable web/VNC
          -e ARCH=${{ matrix.arch }}
          -v ${{ github.workspace }}:/root/workspace

    - name: Install Termux and build APK
      run: |
        # Wait for emulator to fully boot
        adb wait-for-device
        while [[ -z $(adb shell getprop sys.boot_completed) ]]; do sleep 5; done

        # Install Termux and run script
        adb install termux.apk
        adb push myscript.sh /data/data/com.termux/files/home/
        adb shell "cd /data/data/com.termux/files/home && ./myscript.sh"

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: sm64coopdx-${{ matrix.arch }}
        path: sm64coopdx-${{ matrix.arch }}.apk
