name: Build APK with Valid Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armv7, arm64]  # Build for both architectures
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Start Android emulator
      uses: docker://docker:emulator
      with:
        args: >
          -e ANDROID_DEVICE="Nexus 5"
          -e EMULATOR_ARGS="-no-window -no-audio -no-boot-anim"
          -e ARCH=${{ matrix.arch }}  # armv7 uses Houdini; arm64 uses native emulation
          -v ${{ github.workspace }}:/root/workspace

    - name: Install Termux and build APK
      run: |
        # Install Termux and push your script
        adb install termux.apk
        adb push myscript.sh /data/data/com.termux/files/home/
        adb shell "cd /data/data/com.termux/files/home && ./myscript.sh"

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: sm64coopdx-${{ matrix.arch }}
        path: sm64coopdx-${{ matrix.arch }}.apk
